export function routerAsynFunc(file) {
    /*异步路由*/
    return routerAsyn[file];
};

const routerAsyn = {
    'enter/index': r => require.ensure([], () => r(require(`../views/enter/index`)), `nongye/nongye-enter`),
    'home/index': r => require.ensure([], () => r(require(`../views/home/index`)), `nongye/nongye-home`),
    'page/index': r => require.ensure([], () => r(require(`../views/page/index`)), `nongye/nongye-page`),
    'monitor/index': r => require.ensure([], () => r(require(`../views/monitor/index`)), `nongye/nongye-monitor`),
    'map_monitor/index': r => require.ensure([], () => r(require(`../views/map_monitor/index`)), `nongye/nongye-map-monitor`),
    'map_monitor/view': r => require.ensure([], () => r(require(`../views/map_monitor/view`)), `nongye/nongye-map-monitor`),
    'map_project/index': r => require.ensure([], () => r(require(`../views/map_project/index`)), `nongye/nongye-map-project`),
    'page_monitor/index': r => require.ensure([], () => r(require(`../views/page_monitor/index`)), `nongye/nongye-page-monitor`),
    'page_realwarning/index': r => require.ensure([], () => r(require(`../views/page_realwarning/index`)), `nongye/nongye-page-realwarning`),
    'page_warnlog/index': r => require.ensure([], () => r(require(`../views/page_warnlog/index`)), `nongye/nongye-page-warnlog`),
    'area/index': r => require.ensure([], () => r(require(`../views/area/index`)), `nongye/area`),
    'rolemanage/index': r => require.ensure([], () => r(require(`../views/rolemanage/index`)), `nongye/rolemanage`),
    'rolemanage/add': r => require.ensure([], () => r(require(`../views/rolemanage/add`)), `nongye/rolemanage/add`),
    'rolemanage/edit': r => require.ensure([], () => r(require(`../views/rolemanage/edit`)), `nongye/rolemanage/edit`),
    'smallprogram/index': r => require.ensure([], () => r(require(`../views/smallprogram/index`)), `nongye/smallprogram`),
    'smallprogram/add': r => require.ensure([], () => r(require(`../views/smallprogram/add`)), `nongye/smallprogram/add`),
    'page_warnnotice/index': r => require.ensure([], () => r(require(`../views/page_warnnotice/index`)), `nongye/page_warnnotice/index`),
    'page_warnnotice/add': r => require.ensure([], () => r(require(`../views/page_warnnotice/add`)), `nongye/page_warnnotice/add`),
    'page_warnnotice/edit': r => require.ensure([], () => r(require(`../views/page_warnnotice/edit`)), `nongye/page_warnnotice/edit`),
    'organization/index': r => require.ensure([], () => r(require(`../views/organization/index`)), `nongye/organization`),
    'organization/edit': r => require.ensure([], () => r(require(`../views/organization/edit`)), `nongye/organization-edit`),
    'user/index': r => require.ensure([], () => r(require(`../views/user/index`)), `nongye/user`),
    'user/add': r => require.ensure([], () => r(require(`../views/user/add`)), `nongye/user-add`),
    'area/add': r => require.ensure([], () => r(require(`../views/area/add`)), `nongye/area-add`),
    'area/edit': r => require.ensure([], () => r(require(`../views/area/edit`)), `nongye/area-edit`),
    'area/list': r => require.ensure([], () => r(require(`../views/area/list`)), `nongye/area-list`),
    'area/detail': r => require.ensure([], () => r(require(`../views/area/detail`)), `nongye/area-detail`),
    'alarmmanage/index': r => require.ensure([], () => r(require(`../views/alarmmanage/index`)), `nongye/nongye-alarmmanage`),
    'system/index': r => require.ensure([], () => r(require(`../views/system/index`)), `nongye/nongye-system`),
    'equipment/index': r => require.ensure([], () => r(require(`../views/equipment/index`)), `nongye/nongye-equipment-index`),
    'equipment/detail': r => require.ensure([], () => r(require(`../views/equipment/detail`)), `nongye/nongye-equipment-detail`),
    'equipment/add': r => require.ensure([], () => r(require(`../views/equipment/add`)), `nongye/nongye-equipment-add`),
    'equipment/edit': r => require.ensure([], () => r(require(`../views/equipment/edit`)), `nongye/nongye-equipment-edit`),
    'equipment/view': r => require.ensure([], () => r(require(`../views/equipment/view`)), `nongye/nongye-equipment-equipmentview`),
    'dailypaper/index': r => require.ensure([], () => r(require(`../views/dailypaper/index`)), `nongye/nongye-dailypaper-index`),
    'dailypaper/add': r => require.ensure([], () => r(require(`../views/dailypaper/add`)), `nongye/nongye-dailypaper-add`),
    'dailypaper/detail': r => require.ensure([], () => r(require(`../views/dailypaper/detail`)), `nongye/nongye-dailypaper-detail`),
    'dailypaper/edit': r => require.ensure([], () => r(require(`../views/dailypaper/edit`)), `nongye/nongye-dailypaper-edit`),
    'farming_flowmanage/index': r => require.ensure([], () => r(require(`../views/farming_flowmanage/index`)), `nongye/nongye-farming_flowmanage-index`),
    'farming_flowmanage/detail': r => require.ensure([], () => r(require(`../views/farming_flowmanage/detail`)), `nongye/nongye-farming_flowmanage-detail`),
    'alarm_setup/index': r => require.ensure([], () => r(require(`../views/alarm_setup/index`)), `nongye/nongye-equipment-setup`),
    'login/index': r => require.ensure([], () => r(require(`../views/login/index`)), `nongye/nongye-login`),
    'login/loginmain/index': r => require.ensure([], () => r(require(`../views/login/loginmain/index`)), `nongye/nongye-login-loginmain`),
    'login/changepassword/index': r => require.ensure([], () => r(require(`../views/login/changepassword/index`)), `nongye/nongye-login-changepassword`),
    'login/fillaccount/index': r => require.ensure([], () => r(require(`../views/login/fillaccount/index`)), `nongye/nongye-login-fillaccount`),
    'login/messageauthentication/index': r => require.ensure([], () => r(require(`../views/login/messageauthentication/index`)), `nongye/nongye-login-messageauthentication`),
    'login/setnewpassword/index': r => require.ensure([], () => r(require(`../views/login/setnewpassword/index`)), `nongye/nongye-login-setnewpassword`),
};
